### ISSUE TITLE
Wanna join forces?

### ISSUE THREAD

**Issue by renich** [bitwigstudio/bitwig-overlay#1]
I have this, man: https://github.com/renich/funtoo-bitwig-studio

Let me know what you think.

**Comment by renich** [comment]
ping @Ridderby

**Comment by Ridderby** [comment]
Hi Renich, 

I am fine with some cooperation. We should not need same ebuilds in two trees. What is you suggestion? 

I am using my ebuild already, how far along are you, I cant find the ebuilds in your tree, only the Manifest file?

**Comment by renich** [comment]
Hey @Ridderby. I am using it as well. Why not create an organization and make us, both, members. We might attract more collaboration if we do so.

Also, how did you deal with jack2? I've discovered a ton of problems and reported them at IRC; where they were confirmed.

In short, BitWig requires jack2; not jack-audio-connection-kit. 

Anyway, just sayin'

**Comment by Ridderby** [comment]
Hi @renich !
I made an organization and invited you. I also forked the repo so that the old link still works. 

Please accept invitation and we can join forces. 

BR
Erik

**Comment by renich** [comment]
Done, man! Resolve this one! ;)

**Comment by renich** [comment]
Still can't push...

```
$ git push origin testing -u
ERROR: Permission to bitwigstudio/bitwig-overlay.git denied to renich.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Ridderby** [comment]
Added you to collaborators and you shall have an invite. Accept and you shall be able to push. I hope :)

**Comment by renich** [comment]
Yep. Pushed to a testing branch so you can check it out and, maybe, merge it. I include version 1.3.14
