### ISSUE TITLE
i cant install bitwig

### ISSUE THREAD

**Issue by billyblackburn** [bitwigstudio/bitwig-overlay#5]
Ive added the repo and i get this 
emerge bitwig-studio

 * IMPORTANT: 3 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

Calculating dependencies... done!

>>> Verifying ebuild manifests

>>> Emerging (1 of 1) media-sound/bitwig-studio-1.3.13::bitwig-overlay

!!! media-sound/bitwig-studio-1.3.13 has fetch restriction turned on.
!!! This probably means that this ebuild's files must be downloaded
!!! manually.  See the comments in the ebuild for more information.

 * Fetch failed for 'media-sound/bitwig-studio-1.3.13', Log file:
 *  '/var/tmp/portage/media-sound/bitwig-studio-1.3.13/temp/build.log'
 * The following are listed in SRC_URI for bitwig-studio:
 *    bitwig-studio-1.3.13.deb

>>> Failed to emerge media-sound/bitwig-studio-1.3.13, Log file:

>>>  '/var/tmp/portage/media-sound/bitwig-studio-1.3.13/temp/build.log'

 * Messages for package media-sound/bitwig-studio-1.3.13:

 * Fetch failed for 'media-sound/bitwig-studio-1.3.13', Log file:
 *  '/var/tmp/portage/media-sound/bitwig-studio-1.3.13/temp/build.log'
 * The following are listed in SRC_URI for bitwig-studio:
 *    bitwig-studio-1.3.13.deb

**Comment by renich** [comment]
Could you try syncing and installing again?

```bash
emaint -A sync && emerge -a bitwig-studio
```

**Comment by billyblackburn** [comment]
sudo emaint -A sync
>>> Syncing repository 'gentoo' into '/usr/portage'...
/usr/bin/git pull
Already up-to-date.
=== Sync completed for gentoo
q: Updating ebuild cache in /usr/portage ... 
q: Finished 39000 entries in 0.212748 seconds

 * IMPORTANT: 3 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.


Action: sync for repo: gentoo, returned code = 0


tertl3@tertl3host ~ $ sudo emerge bitwig-studio

 * IMPORTANT: 3 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

Calculating dependencies... done!

>>> Verifying ebuild manifests

>>> Emerging (1 of 1) media-sound/bitwig-studio-1.3.13::bitwig-overlay

!!! media-sound/bitwig-studio-1.3.13 has fetch restriction turned on.
!!! This probably means that this ebuild's files must be downloaded
!!! manually.  See the comments in the ebuild for more information.

 * Fetch failed for 'media-sound/bitwig-studio-1.3.13', Log file:
 *  '/var/tmp/portage/media-sound/bitwig-studio-1.3.13/temp/build.log'
 * The following are listed in SRC_URI for bitwig-studio:
 *    bitwig-studio-1.3.13.deb

>>> Failed to emerge media-sound/bitwig-studio-1.3.13, Log file:

>>>  '/var/tmp/portage/media-sound/bitwig-studio-1.3.13/temp/build.log'

 * Messages for package media-sound/bitwig-studio-1.3.13:

 * Fetch failed for 'media-sound/bitwig-studio-1.3.13', Log file:
 *  '/var/tmp/portage/media-sound/bitwig-studio-1.3.13/temp/build.log'
 * The following are listed in SRC_URI for bitwig-studio:
 *    bitwig-studio-1.3.13.deb
tertl3@tertl3host ~ $ sudo emerge -a bitwig-studio

 * IMPORTANT: 3 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.


These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  N F   ] media-sound/bitwig-studio-1.3.13 

Fetch instructions for media-sound/bitwig-studio-1.3.13:
 * The following are listed in SRC_URI for bitwig-studio:
 *    bitwig-studio-1.3.13.deb

Would you like to merge these packages? [Yes/No] Yes 

>>> Verifying ebuild manifests

>>> Emerging (1 of 1) media-sound/bitwig-studio-1.3.13::bitwig-overlay

!!! media-sound/bitwig-studio-1.3.13 has fetch restriction turned on.
!!! This probably means that this ebuild's files must be downloaded
!!! manually.  See the comments in the ebuild for more information.

 * Fetch failed for 'media-sound/bitwig-studio-1.3.13', Log file:
 *  '/var/tmp/portage/media-sound/bitwig-studio-1.3.13/temp/build.log'
 * The following are listed in SRC_URI for bitwig-studio:
 *    bitwig-studio-1.3.13.deb

>>> Failed to emerge media-sound/bitwig-studio-1.3.13, Log file:

>>>  '/var/tmp/portage/media-sound/bitwig-studio-1.3.13/temp/build.log'

 * Messages for package media-sound/bitwig-studio-1.3.13:

 * The following are listed in SRC_URI for bitwig-studio:
 *    bitwig-studio-1.3.13.deb

 * Messages for package media-sound/bitwig-studio-1.3.13:

 * Fetch failed for 'media-sound/bitwig-studio-1.3.13', Log file:
 *  '/var/tmp/portage/media-sound/bitwig-studio-1.3.13/temp/build.log'
 * The following are listed in SRC_URI for bitwig-studio:
 *    bitwig-studio-1.3.13.deb
tertl3@tertl3host ~ $

**Comment by renich** [comment]
Yes, it seems that the fetch restriction is in place. We need to get rid of it so it can fetch the source for you.

**Comment by billyblackburn** [comment]
yes, i cloned ur overlay and it worked from there

**Comment by renich** [comment]
@billyblackburn the odd thing is that you're trying to install 1.3.13. 

I'd recommend removing bitwig and the repo, and using the new way of installing overlays: https://wiki.gentoo.org/wiki//etc/portage/repos.conf

Basically, just this

```bash
# setup
mkdir -m 750 /etc/portage/repos.conf
chown root:portage /etc/portage/repos.conf

# install repo
cat << EOF > /etc/portage/repos.conf/bitwig-overlay.conf
[bitwig-overlay]
location = /usr/local/portage/bitwig-overlay
sync-type = git
sync-uri = https://github.com/renich/bitwig-overlay.git
EOF

# sync
emaint -r bitwig-overlay sync
```

This works nicely for me. Aaaand, you'd get the all new 1.3.15 version... and, if you have your beta deb file, you can install 2.0.0beta1... or something.

I'll include instructions on the README as soon as I can.
