### ISSUE TITLE
Bitwig doesn't start with system JRE

### ISSUE THREAD

**Issue by hlzr** [bitwigstudio/bitwig-overlay#6]
I had issues getting Bitwig to start using the portage-installed JRE. Can you help me to figure out what went wrong? 

As a workaround, I modified the ebuild to use the bundled JRE (see my fork).  What's the main advantage of using one JRE over another?

**Comment by renich** [comment]
Why would you want to have two different JREs installed?

What kind of problems did you have? I'd like to know so I could improve.
